name: "create-release"

on:
  workflow_run:
    workflows: ["publish"]
    types:
      - completed
    branches:
      - release
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release for'
        required: true
        type: string

jobs:
  create-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from Cargo.toml
        id: version
        run: |
          VERSION=$(grep "^version" src-tauri/Cargo.toml | head -1 | cut -d '"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=app-v$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || steps.version.outputs.tag }}
          name: "競艇スクレイピング v${{ steps.version.outputs.version }}"
          body: |
            ## 🚤 競艇スクレイピングアプリ v${{ steps.version.outputs.version }}
            
            このリリースには以下のプラットフォーム向けのビルド済みアプリケーションが含まれています：
            
            ### ダウンロード
            - **Windows**: `.exe` ファイル
            - **macOS (Intel)**: `x86_64-apple-darwin` ファイル  
            - **macOS (Apple Silicon)**: `aarch64-apple-darwin` ファイル
            - **Linux**: `AppImage` または `.deb` ファイル
            
            ### 機能
            - 競艇の出走情報スクレイピング
            - レースデータの分析と表示
            - 各種統計データの取得
            
            ### インストール方法
            1. お使いのOS用のファイルをダウンロード
            2. ファイルを実行してインストール
            3. アプリケーションを起動
            
            ### 注意事項
            - このアプリケーションは競艇情報の分析用途で作成されています
            - スクレイピング対象サイトの利用規約をご確認ください
            
            ---
            
            自動生成されたリリースです。詳細な変更履歴は [Commits](https://github.com/${{ github.repository }}/commits) をご確認ください。
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}